mysite/PythonBoard/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    #url(r'^contact/$', views.contact, name='contact'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<topic_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<topic_id>\d+)/reply/(?P<text_no>\d+)/$', views.reply, name='reply'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^signup/$', views.signup, name='signup'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^PythonBoard/', include('PythonBoard.urls', namespace='PythonBoard'))
]

mysite/PythonBoard/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """ Topic Table """
    title = models.CharField(max_length=500)
    register_name = models.CharField(max_length=30)
    register_datetime = models.DateTimeField()
    update_name = models.CharField(max_length=30)
    update_datetime = models.DateTimeField()

    def __str__(self):
        return self.title

class TopicDetail(models.Model):
    """ TopicDetail Table """
    title = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    text_no = models.PositiveIntegerField(blank=False, null=False, default=1)
    register_name = models.CharField(max_length=30)
    register_datetime = models.DateTimeField()
    update_name = models.CharField(max_length=30)
    update_datetime = models.DateTimeField()

mysite/PythonBoard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Topic, TopicDetail

class AccountForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AccountForm, self).__init__(*args, **kwargs)
        self.confirm_password = forms.CharField(
            label='確認',
            max_length=128,
            widget=forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '再度パスワードを入力してください。'
                }
            )
        )
        self.fields['confirm_password'] = self.confirm_password

    class Meta:
        model = User
        fields = ('username', 'password')
        labels = {
            'username': 'ユーザー名',
            'password': 'パスワード',
        }
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'ユーザー名を入力してください。',
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'パスワードを入力してください。',
                }
            ),
        }
        help_texts = {
            'username': '半角英数字、@/./+/-/_ のみ使用可能です。',
        }

    def clean(self):
        """ 確認パスワードのバリデーションチェック """
        cleaned_data = self.cleaned_data
        if 'password' in cleaned_data and 'confirm_password' in cleaned_data:
            if cleaned_data['password'] != cleaned_data['confirm_password']:
                raise forms.ValidationError('パスワードが異なります。')
        return cleaned_data

class TopicForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TopicForm, self).__init__(*args, **kwargs)
        self.text = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 15,
                },
            )
        )
        self.fields['text'] = self.text

    class Meta:
        model = Topic
        fields = ('title',)
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = TopicDetail
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 15,
                }
            )
        }

mysite/PythonBoard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Max
from .models import Topic, TopicDetail
from .forms import AccountForm, TopicForm, ReplyForm
from django.utils import timezone

# Create your views here.

def index(request):
    """ index.html view """
    template = loader.get_template('PythonBoard/index.html')

    topic_num_query = """
                      SELECT
                          COUNT(*)
                      FROM
                          PythonBoard_topicdetail
                      WHERE
                          PythonBoard_topic.id = PythonBoard_topicdetail.title_id
                      """
    topic_list = Topic.objects.order_by('-update_datetime').extra(
        select={'topic_num': topic_num_query}
    )
    context = {
        'signin_username': request.user.username,
        'topics': topic_list,
    }

    return HttpResponse(template.render(context, request))

def about(request):
    """ about.html view """
    template = loader.get_template('PythonBoard/about/about.html')
    context = {
        'signin_username': request.user.username,
    }
    return HttpResponse(template.render(context, request))

def contact(request):
    """ contact.html view """
    template = loader.get_template('PythonBoard/contact/contact.html')
    context = {
        'signin_username': request.user.username,
    }
    return HttpResponse(template.render(context, request))

def detail(request, topic_id):
    """ detail.html view """
    template = loader.get_template('PythonBoard/detail/detail.html')
    try:
        topic_title = Topic.objects.get(pk=topic_id).title
        topic_detail_list = TopicDetail.objects.filter(title=topic_id).order_by('register_datetime')
    except Topic.DoesNotExist:
        raise Http404

    context = {
        'signin_username': request.user.username,
        'topic_title': topic_title,
        'topic_details': topic_detail_list,
        'topic_id': topic_id,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='PythonBoard:signin')
def create(request):
    """ create.html view """
    template = loader.get_template('PythonBoard/create/create.html')
    f = TopicForm()

    if request.method == 'POST':
        f = TopicForm(request.POST)
        now_time = timezone.now()
        if f.is_valid():
            t = Topic(
                title=f.cleaned_data['title'],
                register_name=request.user.username,
                register_datetime=now_time,
                update_name=request.user.username,
                update_datetime=now_time
            )
            t.save()
            td = TopicDetail(
                title=t,
                text=f.cleaned_data['text'],
                register_name=request.user.username,
                register_datetime=now_time,
                update_name=request.user.username,
                update_datetime=now_time
            )
            td.save()
            return redirect('PythonBoard:index')
    context = {
        'signin_username': request.user.username,
        'form': f,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='PythonBoard:signin')
def reply(request, topic_id, text_no=0):
    """ reply.html view """
    template = loader.get_template('PythonBoard/reply/reply.html')

    if request.method == 'POST':
        f = ReplyForm(request.POST)
        now_time = timezone.now()
        if f.is_valid():
            t = Topic.objects.get(pk=topic_id)
            max_no = TopicDetail.objects.filter(title=t).aggregate(Max('text_no'))['text_no__max']
            max_no = int(max_no) + 1
            td = TopicDetail(
                title=t,
                text=f.cleaned_data['text'],
                text_no = max_no,
                register_name=request.user.username,
                register_datetime=now_time,
                update_name=request.user.username,
                update_datetime=now_time
            )
            td.save()
            t.update_datetime = now_time
            t.save()
            return redirect('PythonBoard:detail', topic_id)
    else:
        t = Topic.objects.get(pk=topic_id)
        topic_title = t.title
        rep_text = TopicDetail.objects.get(title=t, text_no=text_no).text
        rep_text = '> ' + rep_text
        rep_text = rep_text.replace('\n', '\n> ')
        f = ReplyForm(initial={'text':rep_text})

    context = {
        'signin_username': request.user.username,
        'form': f,
        'topic_title': topic_title,
        'topic_id': topic_id,
    }
    return HttpResponse(template.render(context, request))

def signin(request):
    """ signin.html view """
    template = loader.get_template('PythonBoard/signin/signin.html')
    f = AccountForm()
    error_message = ''

    if request.method == 'POST':
        f = AccountForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            if user.is_active:
                auth.login(request, user)
                return redirect('PythonBoard:index')
            else:
                error_message = 'そのユーザーは現在使用できません。'
        else:
            error_message = 'ユーザー名またはパスワードが異なります。'
    context = {
        'signin_username': request.user.username,
        'form': f,
        'error_message' : error_message,
    }
    return HttpResponse(template.render(context, request))

def signout(request):
    """ signout.html view """
    auth.logout(request)
    return redirect('PythonBoard:index')

def signup(request):
    """ signup.html view """
    template = loader.get_template('PythonBoard/signup/signup.html')
    f = AccountForm()
    error_message = ''

    if request.method == 'POST':
        f = AccountForm(request.POST)
        if f.is_valid():
            try:
                user = User.objects.create_user(
                    username=f.cleaned_data['username'],
                    password=f.cleaned_data['password'],
                )
                user.save()
                return redirect('PythonBoard:signin')
            except IntegrityError:
                # ユーザー重複チェック
                error_message = 'そのユーザー名は既に使われています。'

    context = {
        'signin_username': request.user.username,
        'form': f,
        'error_message' : error_message,
    }
    return HttpResponse(template.render(context, request))

mysite/PythonBoard/templates/PythonBoard/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="{% static 'PythonBoard/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'PythonBoard/css/bootstrap-theme.min.css' %}" rel="stylesheet">
		<script src="{% static 'PythonBoard/js/jquery-2.2.3.min.js' %}"></script>
		<script src="{% static 'PythonBoard/js/bootstrap.min.js' %}"></script>
		<title>Python Board</title>
		<style>
			body {
				padding-top: 70px;
			}
			header {
			}
			.second-title-space {
				padding-bottom: 10px;
			}
		</style>
		{% block exhead %}
		{% endblock %}
	</head>
	<body>
		<!-- Navigation Start -->
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-pattern">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'PythonBoard:index' %}">Python Board</a>
					<p class="navbar-text ">
					{% if signin_username %}
						こんにちは。{{ signin_username }}さん。
					{% else %}
						こんにちは。ゲストさん。
					{% endif %}
					</p>
				</div>
				<div id="collapse-pattern" class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'PythonBoard:index' %}">Top</a></li>
					<li><a href="{% url 'PythonBoard:about' %}">About</a></li>
					<li class="dropdown">
						<a data-toggle="dropdown" 
							role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'PythonBoard:signin' %}">Sign in</a></li>
							<li><a href="{% url 'PythonBoard:signout' %}">Sign out</a></li>
							<li><a href="{% url 'PythonBoard:signup' %}">Sign up</a></li>
						</ul>
					</li>
				</ul>
				</div>
			</div>
		</nav>
		<!-- Navigation End -->
		<div class="container">
			<!-- Header Start -->
			<header>
				<div class="row">
					<div class="col-sm-12">
						<h1>Python Board</h1>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<p>Pythonについて気軽に話し合おう</p>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<hr style="margin:0px 0px 10px 0px;" >
					</div>
				</div>
			</header>
			<!-- Header End -->

			<!-- Main Start -->
			{% block contents %}
			{% endblock %}
			<!-- Main End -->

			<!-- Footer Start -->
			<footer>
			</footer>
			<!-- Footer End -->
		</div>
	</body>
</html>

mysite/PythonBoard/templates/PythonBoard/index.html
{% extends "base.html" %}
{% block exhead %}
{% endblock %}
{% block contents %}
<p><a href="{% url 'PythonBoard:create' %}"><button type="button" class="btn btn-default">トピックを立てる</button></a></p>
<table class="table table-bordered table-striped">
	<thead>
		<tr class="something">
			<th class="col-md-5">トピック</th>
			<th class="col-md-1">投稿数</th>
			<th class="col-md-2">作成日時</th>
			<th class="col-md-2">更新日時</th>
		</tr>
	</thead>
		{% for topic in topics %}
		<tr class="something">
			<td class="col-md-4"><a href="{% url 'PythonBoard:detail' topic_id=topic.id %}">{{ topic.title }}</a></td>
			<td class="col-md-1">{{ topic.topic_num }}</td>
			<td class="col-md-2">{{ topic.register_name }}<br>{{ topic.register_datetime }}</td>
			<td class="col-md-2">{{ topic.update_name }}<br>{{ topic.update_datetime }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<div class="col-sm-1"></div>
{% endblock %}